#!/usr/bin/env python3
import sys
import json
import paramiko

alert_file = sys.argv[1]
creds = sys.argv[2]        # format : "utilisateur|motdepasse"
target_ip = sys.argv[3]    # IP de Windows

user, password = creds.split("|")

with open(alert_file) as f:
    lines = [l for l in f.read().splitlines() if l.strip()]
alert = json.loads(lines[0])

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(target_ip, username=user, password=password, timeout=10)

cmd = 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "C:\\Program Files (x86)\\ossec-agent\\active-response\\bin\\block-wan-remote.ps1"'
stdin, stdout, stderr = client.exec_command(cmd)
stdout.channel.recv_exit_status()
client.close()
